name: Sonar Scan

on:
  push:
    branches:
      - master
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=javaprojectreachabilitycode -Dsonar.organization=javaprojectreachabilitycode -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN  
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
